MAX_WIDTH = 420  # 425
MAX_HEIGHT = 297  # 300
CANVAS_OFFSET = 10
GEOMETRY_BORDER = 2
LINE_ORG = GEOMETRY_BORDER + int(CANVAS_OFFSET / 2)
RECT_ORG = GEOMETRY_BORDER + int(CANVAS_OFFSET / 2)
MM_PX_CONSTANT = 1
SCENE_MAX_WIDTH = MAX_WIDTH + 2 * GEOMETRY_BORDER + CANVAS_OFFSET
SCENE_MAX_HEIGHT = MAX_HEIGHT + 2 * GEOMETRY_BORDER + CANVAS_OFFSET

